package com.github.lastsunday.service.core.controller;

public interface DefaultExceptionConstant extends SwaggerConstant {

	String ERROR_INFO_SEPARATOR = ",";
	int ERROR_CODE_ARGUMENT_NOT_VALID = 10000;
	int ERROR_CODE_NOT_IMPLEMENT_YET = 10001;
	int ERROR_CODE_UNKNOW_EXCEPTION = 10002;
	int ERROR_CODE_ENTITY_EXISTS = 10010;
	int ERROR_CODE_ENTITY_NOT_EXISTS = 10011;
	int ERROR_CODE_ADD_FAILURE = 10012;
	int ERROR_CODE_DELETE_FAILURE = 10013;
	int ERROR_CODE_UPDATE_FAILURE = 10014;

	int ERROR_CODE_REMOTE_SERVICE_EXCEPTION = 11000;

	String MESSAGE_ARGUMENT_NOT_VALID = ERROR_CODE_ARGUMENT_NOT_VALID + ERROR_INFO_SEPARATOR + "Argument not valid";
	String MESSAGE_NOT_IMPLEMENT_YET = ERROR_CODE_NOT_IMPLEMENT_YET + ERROR_INFO_SEPARATOR + "Not implement yet";
	String MESSAGE_UNKNOW_EXCEPTION = ERROR_CODE_UNKNOW_EXCEPTION + ERROR_INFO_SEPARATOR + "Unknow Exception";

	String MESSAGE_ENTITY_EXISTS = ERROR_CODE_ENTITY_EXISTS + ERROR_INFO_SEPARATOR + "Entity already exists";
	String MESSAGE_ENTITY_NOT_EXISTS = ERROR_CODE_ENTITY_NOT_EXISTS + ERROR_INFO_SEPARATOR + "Entity not exists";
	String MESSAGE_ENTITY_ADD_FAILURE = ERROR_CODE_ADD_FAILURE + ERROR_INFO_SEPARATOR + "Entity add failure";
	String MESSAGE_ENTITY_DELETE_FAILURE = ERROR_CODE_DELETE_FAILURE + ERROR_INFO_SEPARATOR + "Entity delete failure";
	String MESSAGE_ENTITY_UPDATE_FAILURE = ERROR_CODE_UPDATE_FAILURE + ERROR_INFO_SEPARATOR + "Entity update failure";

	String MESSAGE_REMOTE_SERVICE_EXCEPTION = ERROR_CODE_REMOTE_SERVICE_EXCEPTION + ERROR_INFO_SEPARATOR
			+ "Remote service exception";

	// need fill all exception message
	String DEFAULT_COMMON_EXCEPTION_MESSAGE = MESSAGE_ARGUMENT_NOT_VALID + SWAGGER_API_NEWLINE
			+ MESSAGE_NOT_IMPLEMENT_YET + SWAGGER_API_NEWLINE + MESSAGE_UNKNOW_EXCEPTION;;
}
